# -- 코드를 입력하세요
# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY, (A.PRICE * COUNT(*)) AS TOTAL_SALES
# FROM BOOK_SALES B INNER JOIN 
# (SELECT
#     A.BOOK_ID, B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.PRICE
# FROM
#     BOOK A INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
# ) A
# ON A.BOOK_ID = B.BOOK_ID
# WHERE
#     SALES_DATE LIKE '2022-01%'
# GROUP BY
#     A.AUTHOR_ID, A.CATEGORY
# ORDER BY
#     A.AUTHOR_ID, A.CATEGORY DESC

# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL) AS TOTAL_SALES
# FROM
# (
SELECT
    B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM
    BOOK A INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    INNER JOIN BOOK_SALES C ON C.BOOK_ID = A.BOOK_ID
WHERE
    C.SALES_DATE LIKE '2022-01%'
GROUP BY
    AUTHOR_ID, CATEGORY
ORDER BY
    AUTHOR_ID, CATEGORY DESC
# ) sub
# GROUP BY
#     AUTHOR_ID, CATEGORY
# ORDER BY
#     AUTHOR_ID, CATEGORY DESC
    