-- 코드를 작성해주세요
SELECT
    A.ITEM_ID,
    A.ITEM_NAME,
    A.RARITY
FROM
    ITEM_INFO A
WHERE
    A.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL GROUP BY PARENT_ITEM_ID)
ORDER BY A.ITEM_ID DESC
    