-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT os.USER_ID) AS USERS
FROM
    ONLINE_SALE os INNER JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY
    YEAR, MONTH, GENDER