-- 코드를 입력하세요
SELECT
    fp.PRODUCT_ID,
    fp.PRODUCT_NAME,
    fp.PRICE * SUM(fo.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT fp INNER JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE
    fo.PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    PRODUCT_ID, PRODUCT_NAME, PRICE
ORDER BY
    TOTAL_SALES DESC, fp.PRODUCT_ID