-- 코드를 입력하세요
SELECT
    APNT_NO,
    p.PT_NAME,
    p.PT_NO,
    d.MCDP_CD,
    d.DR_NAME,
    a.APNT_YMD
FROM 
    APPOINTMENT a INNER JOIN PATIENT p ON a.PT_NO = p.PT_NO
    INNER JOIN DOCTOR d ON d.DR_ID = a.MDDR_ID 
WHERE
    APNT_CNCL_YN != 'Y' AND APNT_YMD LIKE '2022-04-13%' AND d.MCDP_CD = 'CS'
ORDER BY
    a.APNT_YMD ASC