SELECT 
    MONTH(O.START_DATE) AS MONTH,
    O.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY O
JOIN (
    -- 대여 횟수가 5회 이상인 자동차 ID 목록 조회
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 
      AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) A ON O.CAR_ID = A.CAR_ID
WHERE YEAR(O.START_DATE) = 2022 
  AND MONTH(O.START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH(O.START_DATE), O.CAR_ID
ORDER BY MONTH ASC, O.CAR_ID DESC;
