-- 코드를 입력하세요
SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    BOOK_SALES bs INNER JOIN  BOOK b
    ON bs.BOOK_ID = b.BOOK_ID
WHERE
    bs.SALES_DATE LIKE '2022-01%'
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY ASC