-- 코드를 작성해주세요
SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM
    FISH_INFO A
WHERE A.FISH_TYPE IN (
    SELECT
        B.FISH_TYPE
    FROM 
        (SELECT 
            FISH_TYPE, 
            IF(LENGTH <= 10 OR LENGTH IS NULL, 10,LENGTH) AS LENGTH
         FROM FISH_INFO) B
    GROUP BY
        B.FISH_TYPE
    HAVING
        AVG(B.LENGTH) >= 33
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE ASC

